# Generated by Django 4.2.1 on 2023-05-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APOD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("copyright", models.CharField(blank=True, max_length=100, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("explanation", models.TextField()),
                ("title", models.CharField(max_length=100)),
                ("url", models.URLField(max_length=500)),
            ],
        ),
    ]
